[project]
name = "job-hunting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fpdf2>=2.8.5",
    "httpx>=0.28.1",
    "mcp[cli]>=1.26.0",
]
